### ISSUE TITLE
Missing "ibutsu_utils/_version.py"

### ISSUE THREAD

**Issue by quarckster** [ibutsu/ibutsu-utils#10]
In `pyproject.toml` "ibutsu_utils/_version.py" is specified but there is no such file. Please add this file or replace 

```toml
[tool.hatch.build.hooks.vcs]
version-file = "ibutsu_utils/_version.py"
```

with

```toml
[tool.hatch.version]
source = "vcs"
```
